package controller

import (
	"image"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	"net/http"

	"github.com/naoina/kocha"
)

type Images struct {
	*kocha.DefaultController
}

func (im *Images) GET(c *kocha.Context) kocha.Result {
	// FIXME: auto-generated by kocha
	return kocha.Render(c)
}

func (im *Images) POST(c *kocha.Context) kocha.Result {
	f, h, err := c.Request.FormFile("image")
	if err != nil {
		return kocha.RenderError(c, http.StatusBadRequest)
	}
	defer f.Close()
	for i, v := range h.Header {
		println("=====" + i + "=====")
		for _, w := range v {
			println(w)
		}
	}

	_, fm, err := image.Decode(f)
	if err != nil {
		return kocha.RenderError(c, http.StatusBadRequest)
	}
	println(fm)

	// TODO 配置用のパス決める

	// TODO S3に配置

	// TODO DBにIDを保存

	// FIXME remove nil
	return kocha.Render(c, kocha.Data{"imagePath": nil})
}

func (im *Images) PUT(c *kocha.Context) kocha.Result {
	// FIXME: auto-generated by kocha
	//iid := c.Params.Get("imageId")
	return kocha.Render(c)
}

func (im *Images) DELETE(c *kocha.Context) kocha.Result {
	// FIXME: auto-generated by kocha
	//iid := c.Params.Get("imageId")
	return kocha.Render(c)
}
